import type { ExtractedMenuModel } from "./schema";

export const SAMPLE_MENU_MODEL: ExtractedMenuModel = {
  restaurantName: "Juniper & Ember",
  currency: "USD",
  dishes: [
    { name: "Miso Butter Ramen", description: "Roasted mushroom, sweet corn, jammy egg, scallion and chile crisp.", price: 19, category: "Noodles", cuisine: "Japanese", ingredients: ["miso", "butter", "ramen noodles", "mushroom", "egg", "chile crisp"], sweet: .22, salty: .65, sour: .08, bitter: .12, umami: .94, spicy: .48, rich: .82, fresh: .25, crispy: .35, creamy: .64, chewy: .62, smoky: .2, proteinTypes: ["egg"], carbohydrateTypes: ["noodles"], cookingMethods: ["simmered", "roasted"], confidence: .94, unknownFields: [] },
    { name: "Charred Harissa Chicken", description: "Herb couscous, preserved lemon, cucumber and garlic yogurt.", price: 24, category: "Mains", cuisine: "North African", ingredients: ["chicken", "harissa", "couscous", "lemon", "cucumber", "yogurt"], sweet: .12, salty: .48, sour: .58, bitter: .08, umami: .62, spicy: .74, rich: .45, fresh: .7, crispy: .2, creamy: .42, chewy: .25, smoky: .78, proteinTypes: ["chicken", "dairy"], carbohydrateTypes: ["couscous"], cookingMethods: ["grilled", "charred"], confidence: .92, unknownFields: [] },
    { name: "Crispy Maitake Tacos", description: "Corn tortillas, avocado crema, pickled onion and salsa macha.", price: 16, category: "Tacos", cuisine: "Mexican", ingredients: ["maitake mushroom", "corn tortilla", "avocado", "pickled onion", "salsa macha"], sweet: .15, salty: .4, sour: .58, bitter: .16, umami: .72, spicy: .66, rich: .42, fresh: .62, crispy: .9, creamy: .48, chewy: .24, smoky: .38, proteinTypes: ["mushroom"], carbohydrateTypes: ["corn tortilla"], cookingMethods: ["fried", "pickled"], confidence: .9, unknownFields: [] },
    { name: "Citrus Salmon Crudo", description: "Fennel, grapefruit, serrano and toasted sesame.", price: 18, category: "Starters", cuisine: "Contemporary", ingredients: ["salmon", "fennel", "grapefruit", "serrano", "sesame"], sweet: .24, salty: .34, sour: .8, bitter: .22, umami: .48, spicy: .35, rich: .36, fresh: .96, crispy: .18, creamy: .2, chewy: .2, smoky: .08, proteinTypes: ["fish"], carbohydrateTypes: [], cookingMethods: ["raw"], confidence: .92, unknownFields: [] },
    { name: "Truffle Mac & Cheese", description: "Aged cheddar, black truffle and toasted sourdough crumbs.", price: 17, category: "Mains", cuisine: "American", ingredients: ["pasta", "cheddar", "truffle", "sourdough"], sweet: .1, salty: .65, sour: .08, bitter: .12, umami: .86, spicy: .05, rich: .97, fresh: .08, crispy: .38, creamy: .95, chewy: .45, smoky: .12, proteinTypes: ["dairy"], carbohydrateTypes: ["pasta", "bread"], cookingMethods: ["baked"], confidence: .95, unknownFields: [] },
    { name: "Grilled Peach Salad", description: "Arugula, burrata, pistachio and balsamic.", price: 15, category: "Salads", cuisine: "Italian", ingredients: ["peach", "arugula", "burrata", "pistachio", "balsamic"], sweet: .62, salty: .28, sour: .5, bitter: .34, umami: .24, spicy: .05, rich: .38, fresh: .9, crispy: .28, creamy: .6, chewy: .16, smoky: .38, proteinTypes: ["dairy"], carbohydrateTypes: ["fruit"], cookingMethods: ["grilled", "raw"], confidence: .9, unknownFields: [] },
    { name: "Tahini Chocolate Tart", description: "Dark chocolate ganache, sesame caramel and sea salt.", price: 11, category: "Desserts", cuisine: "Dessert", ingredients: ["dark chocolate", "tahini", "sesame", "caramel"], sweet: .82, salty: .34, sour: .05, bitter: .4, umami: .2, spicy: .02, rich: .96, fresh: .05, crispy: .32, creamy: .86, chewy: .24, smoky: .08, proteinTypes: ["dairy"], carbohydrateTypes: ["pastry"], cookingMethods: ["baked"], confidence: .94, unknownFields: [] },
  ],
};
